// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://delgbpqcbmxtvvvgsnmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlbGdicHFjYm14dHZ2dmdzbm1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1ODQyMTgsImV4cCI6MjA3NTE2MDIxOH0.Rquc0-Kn-NheJAYR4mzDYoczmAljudDm09Vs_5y9Nsg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});